# Verbosity control
/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/gps/verbose 2

# General Particle Soure setup
/gps/direction 0 0 -1
/gps/particle e-
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 -190 cm
/gps/pos/radius 70 cm
#/gps/ang/type cos
/gps/ene/type Lin
/gps/ene/min 0.2 GeV
/gps/ene/max 15 GeV
/gps/ene/gradient 0
/gps/ene/intercept 1

# Run simulation
/run/beamOn 100

